npaths: 100000
nreads: 3000000
nreplicates: 5

sampleBreakpoints: "../data/sampleBreakpoints.out"
sampleEdges: "../data/sampleEdges.out"
ref: "../data/reference.fasta"
ref_dir: "../data/reference"
read_length: 100

senses:
  - neg

seeds:
  - 0
  - 1
  - 2
  - 3
  - 4

rep:
  - "01"
  - "02"
  - "03"
  - "04"
  - "05"

samplingFrequency: 10
timelimit: 1800
nthreads: 1
sj_threshold: 120
ntranscripts: 50
